services:
  airgap:
    build:
      context: .
      args:
        - PASSWD
        - HOST_PWD
    environment:
      - PASSWD
      - HOST_PWD
    volumes:
      - ./share:/mnt/share:rw
      - local_bin:/usr/local/bin
      - etc:/etc/
      - cardano:/home/cardano
    network_mode: none

volumes:
  cardano:
    driver: local
  local_bin:
    driver: local
  etc:
    driver: local
