services:
  airgap:
    build:
      context: .
    volumes:
      - ./share:/mnt/share:rw
      - local_bin:/usr/local/bin
      - etc:/etc/
      - ./cardano:/home/cardano
    network_mode: none

volumes:
  local_bin:
    driver: local
  etc:
    driver: local
