name: release

on:
  workflow_dispatch:
  # release:
  #   types: [published]

jobs:
  build:
    name: Create Archive
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: echo "RELEASE_FILENAME=cardano-airgap.zip" >> $GITHUB_ENV

      - name: Create zip file
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: ${{ env.RELEASE_FILENAME }}
          exclusions: '*.git*'

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: cardano-airgap.zip

      - name: Put zip info to Release.txt
        run: |
          echo "\`\`\`json" >> Release.txt
          echo "{" >> Release.txt
          echo "  \"download_size\": $(stat --printf=%s cardano-airgap.zip)," >> Release.txt
          echo "  \"download_sha256\": \"$(sha256sum cardano-airgap.zip | cut -d ' ' -f 1)\"," >> Release.txt
          echo "  \"download_url\": \"${{ fromJSON(steps.upload-assets.outputs.assets)[0].browser_download_url }}\"," >> Release.txt
          echo "  \"install_size\": $([[ "$(zipinfo -t cardano-airgap.zip)" =~ ^[0-9]+\ files,\ ([0-9]+)\ bytes.*$ ]]; echo ${BASH_REMATCH[1]})" >> Release.txt
          echo "}" >> Release.txt
          echo "\`\`\`" >> Release.txt
          
      - name: Update body of release
        uses: softprops/action-gh-release@v2
        with:
          append_body: true
          body_path: Release.txt
          
