name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true

  # release:
  #   types: [published]

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkoout
        uses: actions/checkout@v4

      - name: Get tag name
        run: echo "TAG_NAME=${{ inputs.tag }}" >> $GITHUB_ENV

      - name: PrintReleaseName
        run: echo "RELEASE_FILENAME=cardano-airgap.zip" >> $GITHUB_ENV

      - name: Run Release Script
        run: ./release.sh ${{inputs.tag}}

      - name: Check Release
        run: ls -l ./release

      - name: Publish Release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: |
          cd ./release
          gh release upload "${{ needs.release.outputs.tag }}" "airgap-${{ inputs.tag }}.tar.gz" 
          gh release upload "${{ needs.release.outputs.tag }}" "airgap-usb-${{ inputs.tag }}.tar.gz"
          gh release upload "${{ needs.release.outputs.tag }}" "airgap-checksum.txt" 
        
