name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "バージョン番号"
        required: true
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: read

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release')
    runs-on: ubuntu-latest

    steps:
      - name: Checkoout
        uses: actions/checkout@v4

      - name: Create Release Tag And Note
        env:
          GITHUB_TOKEN: ${{ github.token }}
          RELEASE_TAG: ${{ github.event.pull_request.title }}
        uses: release-drafter/release-drafter@v6
        with:
          tag: ${{ env.RELEASE_TAG }}
          name: Release ${{ env.RELEASE_TAG }}
          version: ${{ env.RELEASE_TAG }}
          publish: true
#        run: |
#          gh release create '${{ inputs.tag }}' --repo '${{ github.repository }}' --notes ""

      - name: Run Release Script
        env:
          RELEASE_TAG: ${{ github.event.pull_request.title }}
        run: ./release.sh ${{ env.RELEASE_TAG }}

      - name: Check Release
        run: ls -l ./release

      - name: Publish Release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          RELEASE_TAG: ${{ github.event.pull_request.title }}
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repository: ${{ github.repository }}
          files: |
            release/**
        
